// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_REMI_WebApi.Datos;

#nullable disable

namespace Proyecto_REMI_WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250930235658_usuario")]
    partial class usuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.categoria", b =>
                {
                    b.Property<int>("codigoCategorias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigoCategorias"));

                    b.Property<string>("nombreCategorias")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.HasKey("codigoCategorias")
                        .HasName("PK__categori__612FD8B17F0BC168");

                    b.ToTable("categorias");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.cliente", b =>
                {
                    b.Property<string>("documentoCliente")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("apellidoCliente")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("correoCliente")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("nombreCliente")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("telefonoCliente")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("tipoDocumentoCliente")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.HasKey("documentoCliente")
                        .HasName("PK__cliente__21348785AC5F7CB2");

                    b.ToTable("cliente");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.detallesPedido", b =>
                {
                    b.Property<int>("codigoPedido")
                        .HasColumnType("int");

                    b.Property<int>("codigoProducto")
                        .HasColumnType("int");

                    b.Property<double>("cantidadProducto")
                        .HasColumnType("float");

                    b.Property<double>("totalPagoProducto")
                        .HasColumnType("float");

                    b.Property<double>("valorProducto")
                        .HasColumnType("float");

                    b.HasKey("codigoPedido", "codigoProducto")
                        .HasName("PK__detalles__0A1ABEFCC921DE8B");

                    b.HasIndex("codigoProducto");

                    b.ToTable("detallesPedido");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.detallesRecibo", b =>
                {
                    b.Property<int>("codigoReciboVenta")
                        .HasColumnType("int");

                    b.Property<int>("codigoProducto")
                        .HasColumnType("int");

                    b.Property<double>("cantidadProductoRecibo")
                        .HasColumnType("float");

                    b.Property<double>("totalProductoRecibo")
                        .HasColumnType("float");

                    b.Property<double>("valorUnitarioRecibo")
                        .HasColumnType("float");

                    b.HasKey("codigoReciboVenta", "codigoProducto")
                        .HasName("PK__detalles__A884E8EF75E22B97");

                    b.HasIndex("codigoProducto");

                    b.ToTable("detallesRecibo");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.entradaProducto", b =>
                {
                    b.Property<int>("codigoEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigoEntrada"));

                    b.Property<string>("codigoProveedor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly>("fechaEntrada")
                        .HasColumnType("date");

                    b.Property<string>("numeroFacturaEntrada")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.HasKey("codigoEntrada")
                        .HasName("PK__entradaP__F48E68AAC78E1E82");

                    b.HasIndex("codigoProveedor");

                    b.ToTable("entradaProducto");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.formaPago", b =>
                {
                    b.Property<int>("codigoFormaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigoFormaPago"));

                    b.Property<string>("nombreFormaPago")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.HasKey("codigoFormaPago")
                        .HasName("PK__formaPag__48B185D30D670718");

                    b.ToTable("formaPago");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.movimientosStock", b =>
                {
                    b.Property<int>("codigoMovimientoStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigoMovimientoStock"));

                    b.Property<int?>("codigoEntrada")
                        .HasColumnType("int");

                    b.Property<int?>("codigoReciboVenta")
                        .HasColumnType("int");

                    b.Property<int>("codigoStock")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaMovimientoStock")
                        .HasColumnType("datetime");

                    b.Property<string>("referenciaMovimientoStock")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("tipoMovimientoStock")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.HasKey("codigoMovimientoStock")
                        .HasName("PK__movimien__0C6251D60FE04731");

                    b.HasIndex("codigoEntrada");

                    b.HasIndex("codigoReciboVenta");

                    b.HasIndex("codigoStock");

                    b.ToTable("movimientosStock");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.niveles", b =>
                {
                    b.Property<int>("codigoNivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigoNivel"));

                    b.Property<string>("nombreNivel")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.HasKey("codigoNivel")
                        .HasName("PK__niveles__D9D29D0CF09F9E6C");

                    b.ToTable("niveles");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.pedido", b =>
                {
                    b.Property<int>("codigoPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigoPedido"));

                    b.Property<string>("documentoCliente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("estadoPedido")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateOnly>("fechaPedido")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("horaPedido")
                        .HasColumnType("time");

                    b.Property<double>("valorPedido")
                        .HasColumnType("float");

                    b.HasKey("codigoPedido")
                        .HasName("PK__pedidos__01D75982835F2DCC");

                    b.HasIndex("documentoCliente");

                    b.ToTable("pedidos");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.producto", b =>
                {
                    b.Property<int>("codigoProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigoProducto"));

                    b.Property<int>("codigoSubCategorias")
                        .HasColumnType("int");

                    b.Property<string>("documentoProveedor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("entradaProducto")
                        .HasColumnType("int");

                    b.Property<string>("marcaProducto")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("nombreProducto")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<double?>("precioProducto")
                        .HasColumnType("float");

                    b.Property<int?>("salidaProducto")
                        .HasColumnType("int");

                    b.HasKey("codigoProducto")
                        .HasName("PK__producto__BCDE77E131A25745");

                    b.HasIndex("codigoSubCategorias");

                    b.HasIndex("documentoProveedor");

                    b.ToTable("producto");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.productoEntrada", b =>
                {
                    b.Property<int>("codigoProducto")
                        .HasColumnType("int");

                    b.Property<int>("codigoEntrada")
                        .HasColumnType("int");

                    b.Property<int>("cantidadProductoEntrada")
                        .HasColumnType("int");

                    b.Property<double>("totalProductoEntrada")
                        .HasColumnType("float");

                    b.Property<double>("valorUnitarioProductoEntrada")
                        .HasColumnType("float");

                    b.HasKey("codigoProducto", "codigoEntrada")
                        .HasName("PK__producto__0396916B49461B0F");

                    b.HasIndex("codigoEntrada");

                    b.ToTable("productoEntrada");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.proveedores", b =>
                {
                    b.Property<string>("documentoProveedor")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("correoProveedor")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("nombreProveedor")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("telefonoProveedor")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("tipoDocumentoProveedor")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.HasKey("documentoProveedor")
                        .HasName("PK__proveedo__693B041D2588F88B");

                    b.ToTable("proveedores");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.reciboPago", b =>
                {
                    b.Property<int>("codigoReciboVenta")
                        .HasColumnType("int");

                    b.Property<int>("codigoFormaPago")
                        .HasColumnType("int");

                    b.Property<double>("valorPago")
                        .HasColumnType("float");

                    b.HasKey("codigoReciboVenta", "codigoFormaPago")
                        .HasName("PK__reciboPa__87C217CC60D04857");

                    b.HasIndex("codigoFormaPago");

                    b.ToTable("reciboPagos");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.reciboVenta", b =>
                {
                    b.Property<int>("codigoReciboVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigoReciboVenta"));

                    b.Property<int>("codigoPedido")
                        .HasColumnType("int");

                    b.Property<DateOnly>("fechaReciboVenta")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("horaReciboVenta")
                        .HasColumnType("time");

                    b.Property<double>("totalVenta")
                        .HasColumnType("float");

                    b.Property<double>("valorVenta")
                        .HasColumnType("float");

                    b.HasKey("codigoReciboVenta")
                        .HasName("PK__reciboVe__A3490F91903EC6B6");

                    b.HasIndex("codigoPedido");

                    b.ToTable("reciboVenta");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.salidaProducto", b =>
                {
                    b.Property<int>("codigoReciboVenta")
                        .HasColumnType("int");

                    b.Property<int>("codigoProducto")
                        .HasColumnType("int");

                    b.Property<string>("cantidadSalidaProducto")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.HasKey("codigoReciboVenta", "codigoProducto")
                        .HasName("PK__salidaPr__A884E8EF457C5AE9");

                    b.HasIndex("codigoProducto");

                    b.ToTable("salidaProducto");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.stock", b =>
                {
                    b.Property<int>("codigoStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigoStock"));

                    b.Property<int>("cantidadActual")
                        .HasColumnType("int");

                    b.Property<int>("codigoProducto")
                        .HasColumnType("int");

                    b.Property<byte>("estadoStock")
                        .HasColumnType("tinyint");

                    b.Property<int>("stockMax")
                        .HasColumnType("int");

                    b.Property<int>("stockMin")
                        .HasColumnType("int");

                    b.HasKey("codigoStock")
                        .HasName("PK__stock__9341CE2E87F21FBF");

                    b.HasIndex("codigoProducto");

                    b.ToTable("stock");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.subCategoria", b =>
                {
                    b.Property<int>("codigoSubCategorias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigoSubCategorias"));

                    b.Property<int>("codigoCategorias")
                        .HasColumnType("int");

                    b.Property<string>("nombreSubCategorias")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.HasKey("codigoSubCategorias")
                        .HasName("PK__subCateg__49277B855EFC3AFD");

                    b.HasIndex("codigoCategorias");

                    b.ToTable("subCategorias");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.usuario", b =>
                {
                    b.Property<string>("documentoUsuario")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("apellidoUsuario")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<int>("codigoNivel")
                        .HasColumnType("int");

                    b.Property<string>("correoUsuario")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("nombreUsuario")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("tipoDocumentoUsuario")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.HasKey("documentoUsuario")
                        .HasName("PK__usuario__F1843332CDBA3BE9");

                    b.HasIndex("codigoNivel");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.detallesPedido", b =>
                {
                    b.HasOne("Proyecto_REMI_WebApi.Models.pedido", "codigoPedidoNavigation")
                        .WithMany("detallesPedidos")
                        .HasForeignKey("codigoPedido")
                        .IsRequired()
                        .HasConstraintName("FK_detalles_pedidos");

                    b.HasOne("Proyecto_REMI_WebApi.Models.producto", "codigoProductoNavigation")
                        .WithMany("detallesPedidos")
                        .HasForeignKey("codigoProducto")
                        .IsRequired()
                        .HasConstraintName("FK_detalles_producto");

                    b.Navigation("codigoPedidoNavigation");

                    b.Navigation("codigoProductoNavigation");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.detallesRecibo", b =>
                {
                    b.HasOne("Proyecto_REMI_WebApi.Models.producto", "codigoProductoNavigation")
                        .WithMany("detallesRecibos")
                        .HasForeignKey("codigoProducto")
                        .IsRequired()
                        .HasConstraintName("FK_detallesRecibo_producto");

                    b.HasOne("Proyecto_REMI_WebApi.Models.reciboVenta", "codigoReciboVentaNavigation")
                        .WithMany("detallesRecibos")
                        .HasForeignKey("codigoReciboVenta")
                        .IsRequired()
                        .HasConstraintName("FK_detallesRecibo_reciboVenta");

                    b.Navigation("codigoProductoNavigation");

                    b.Navigation("codigoReciboVentaNavigation");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.entradaProducto", b =>
                {
                    b.HasOne("Proyecto_REMI_WebApi.Models.proveedores", "codigoProveedorNavigation")
                        .WithMany("entradaProductos")
                        .HasForeignKey("codigoProveedor")
                        .IsRequired()
                        .HasConstraintName("FK_entradaProducto_proveedores");

                    b.Navigation("codigoProveedorNavigation");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.movimientosStock", b =>
                {
                    b.HasOne("Proyecto_REMI_WebApi.Models.entradaProducto", "codigoEntradaNavigation")
                        .WithMany("movimientosStocks")
                        .HasForeignKey("codigoEntrada")
                        .HasConstraintName("FK_movimientosStock_entradaProducto");

                    b.HasOne("Proyecto_REMI_WebApi.Models.reciboVenta", "codigoReciboVentaNavigation")
                        .WithMany("movimientosStocks")
                        .HasForeignKey("codigoReciboVenta")
                        .HasConstraintName("FK_movimientosStock_reciboVenta");

                    b.HasOne("Proyecto_REMI_WebApi.Models.stock", "codigoStockNavigation")
                        .WithMany("movimientosStocks")
                        .HasForeignKey("codigoStock")
                        .IsRequired()
                        .HasConstraintName("FK_movimientosStock_stock");

                    b.Navigation("codigoEntradaNavigation");

                    b.Navigation("codigoReciboVentaNavigation");

                    b.Navigation("codigoStockNavigation");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.pedido", b =>
                {
                    b.HasOne("Proyecto_REMI_WebApi.Models.cliente", "documentoClienteNavigation")
                        .WithMany("pedidos")
                        .HasForeignKey("documentoCliente")
                        .IsRequired()
                        .HasConstraintName("FK_pedidos_cliente");

                    b.Navigation("documentoClienteNavigation");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.producto", b =>
                {
                    b.HasOne("Proyecto_REMI_WebApi.Models.subCategoria", "codigoSubCategoriasNavigation")
                        .WithMany("productos")
                        .HasForeignKey("codigoSubCategorias")
                        .IsRequired()
                        .HasConstraintName("FK_producto_subCategorias");

                    b.HasOne("Proyecto_REMI_WebApi.Models.proveedores", "documentoProveedorNavigation")
                        .WithMany("productos")
                        .HasForeignKey("documentoProveedor")
                        .IsRequired()
                        .HasConstraintName("FK_producto_proveedores");

                    b.Navigation("codigoSubCategoriasNavigation");

                    b.Navigation("documentoProveedorNavigation");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.productoEntrada", b =>
                {
                    b.HasOne("Proyecto_REMI_WebApi.Models.entradaProducto", "codigoEntradaNavigation")
                        .WithMany("productoEntrada")
                        .HasForeignKey("codigoEntrada")
                        .IsRequired()
                        .HasConstraintName("FK_productoEntrada_entradaProducto");

                    b.HasOne("Proyecto_REMI_WebApi.Models.producto", "codigoProductoNavigation")
                        .WithMany("productoEntrada")
                        .HasForeignKey("codigoProducto")
                        .IsRequired()
                        .HasConstraintName("FK_productoEntrada_producto");

                    b.Navigation("codigoEntradaNavigation");

                    b.Navigation("codigoProductoNavigation");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.reciboPago", b =>
                {
                    b.HasOne("Proyecto_REMI_WebApi.Models.formaPago", "codigoFormaPagoNavigation")
                        .WithMany("reciboPagos")
                        .HasForeignKey("codigoFormaPago")
                        .IsRequired()
                        .HasConstraintName("FK_reciboPagos_formaPago");

                    b.HasOne("Proyecto_REMI_WebApi.Models.reciboVenta", "codigoReciboVentaNavigation")
                        .WithMany("reciboPagos")
                        .HasForeignKey("codigoReciboVenta")
                        .IsRequired()
                        .HasConstraintName("FK_reciboPagos_reciboVenta");

                    b.Navigation("codigoFormaPagoNavigation");

                    b.Navigation("codigoReciboVentaNavigation");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.reciboVenta", b =>
                {
                    b.HasOne("Proyecto_REMI_WebApi.Models.pedido", "codigoPedidoNavigation")
                        .WithMany("reciboVenta")
                        .HasForeignKey("codigoPedido")
                        .IsRequired()
                        .HasConstraintName("FK_reciboVenta_pedidos");

                    b.Navigation("codigoPedidoNavigation");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.salidaProducto", b =>
                {
                    b.HasOne("Proyecto_REMI_WebApi.Models.producto", "codigoProductoNavigation")
                        .WithMany("salidaProductos")
                        .HasForeignKey("codigoProducto")
                        .IsRequired()
                        .HasConstraintName("FK_salidaProducto_producto");

                    b.HasOne("Proyecto_REMI_WebApi.Models.reciboVenta", "codigoReciboVentaNavigation")
                        .WithMany("salidaProductos")
                        .HasForeignKey("codigoReciboVenta")
                        .IsRequired()
                        .HasConstraintName("FK_salidaProducto_reciboVenta");

                    b.Navigation("codigoProductoNavigation");

                    b.Navigation("codigoReciboVentaNavigation");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.stock", b =>
                {
                    b.HasOne("Proyecto_REMI_WebApi.Models.producto", "codigoProductoNavigation")
                        .WithMany("stocks")
                        .HasForeignKey("codigoProducto")
                        .IsRequired()
                        .HasConstraintName("FK_stock_producto");

                    b.Navigation("codigoProductoNavigation");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.subCategoria", b =>
                {
                    b.HasOne("Proyecto_REMI_WebApi.Models.categoria", "codigoCategoriasNavigation")
                        .WithMany("subCategoria")
                        .HasForeignKey("codigoCategorias")
                        .IsRequired()
                        .HasConstraintName("FK_subCategorias_categorias");

                    b.Navigation("codigoCategoriasNavigation");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.usuario", b =>
                {
                    b.HasOne("Proyecto_REMI_WebApi.Models.niveles", "codigoNivelNavigation")
                        .WithMany("usuarios")
                        .HasForeignKey("codigoNivel")
                        .IsRequired()
                        .HasConstraintName("FK_usuario_niveles");

                    b.Navigation("codigoNivelNavigation");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.categoria", b =>
                {
                    b.Navigation("subCategoria");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.cliente", b =>
                {
                    b.Navigation("pedidos");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.entradaProducto", b =>
                {
                    b.Navigation("movimientosStocks");

                    b.Navigation("productoEntrada");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.formaPago", b =>
                {
                    b.Navigation("reciboPagos");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.niveles", b =>
                {
                    b.Navigation("usuarios");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.pedido", b =>
                {
                    b.Navigation("detallesPedidos");

                    b.Navigation("reciboVenta");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.producto", b =>
                {
                    b.Navigation("detallesPedidos");

                    b.Navigation("detallesRecibos");

                    b.Navigation("productoEntrada");

                    b.Navigation("salidaProductos");

                    b.Navigation("stocks");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.proveedores", b =>
                {
                    b.Navigation("entradaProductos");

                    b.Navigation("productos");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.reciboVenta", b =>
                {
                    b.Navigation("detallesRecibos");

                    b.Navigation("movimientosStocks");

                    b.Navigation("reciboPagos");

                    b.Navigation("salidaProductos");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.stock", b =>
                {
                    b.Navigation("movimientosStocks");
                });

            modelBuilder.Entity("Proyecto_REMI_WebApi.Models.subCategoria", b =>
                {
                    b.Navigation("productos");
                });
#pragma warning restore 612, 618
        }
    }
}
